on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Run all test
        run: npm install && npm run test

      - name: Build front
        run: yarn add react-scripts && yarn add react-router-dom && yarn add graphql && yarn build

      - name: Create zip file of bdyment-portfolio-front
        run: zip -r bdyment-portfolio-front.zip build

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bdyment-portfolio-front.zip
          asset_name: bdyment-portfolio-front.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
